export const APP = {
  SET_SUSPEND_STATUS: 'SET_SUSPEND_STATUS',
  SET_NETWORK_STATUS: 'SET_NETWORK_STATUS',
  SET_UPDATE_STATUS: 'SET_UPDATE_STATUS',
  SET_LOGIN_DIALOG: 'SET_LOGIN_DIALOG',
  SHOW_AUTH_DIALOG: 'SHOW_AUTH_DIALOG',
  SHOW_URL_SCHEME_MODAL: 'SHOW_URL_SCHEME_MODAL',
  SUBMIT_CREDENTIALS: 'SUBMIT_CREDENTIALS',
  SHOW_TRAY_BALLOON: 'SHOW_TRAY_BALLOON',
  TOGGLE_DEV_TOOLS: 'TOGGLE_DEV_TOOLS',
  SELECT_TEAM: 'SELECT_TEAM',
  SELECT_TEAM_BY_USER_ID: 'SELECT_TEAM_BY_USER_ID',
  SELECT_TEAM_BY_INDEX: 'SELECT_TEAM_BY_INDEX',
  SET_TEAMS_BY_INDEX: 'SET_TEAMS_BY_INDEX',
  LOAD_TEAMS: 'LOAD_TEAMS',
  SELECT_CHANNEL: 'SELECT_CHANNEL',
  SELECT_NEXT_TEAM: 'SELECT_NEXT_TEAM',
  SELECT_PREVIOUS_TEAM: 'SELECT_PREVIOUS_TEAM',
  SAVE_WINDOW_SETTINGS: 'SAVE_WINDOW_SETTINGS',
  RESET_STORE: 'RESET_STORE',
  UPDATE_NO_DRAG_REGION: 'UPDATE_NO_DRAG_REGION',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN'
};

export const DOWNLOADS = {
  START_DOWNLOAD: 'START_DOWNLOAD',
  CANCEL_DOWNLOAD: 'CANCEL_DOWNLOAD',
  RETRY_DOWNLOAD: 'RETRY_DOWNLOAD',
  REVEAL_DOWNLOAD: 'REVEAL_DOWNLOAD',
  CLEAR_DOWNLOADS: 'CLEAR_DOWNLOADS',
  DOWNLOAD_STARTED: 'DOWNLOAD_STARTED',
  DOWNLOAD_FINISHED: 'DOWNLOAD_FINISHED'
};

export const EVENTS = {
  EDITING_COMMAND: 'EDITING_COMMAND',
  APP_COMMAND: 'APP_COMMAND',
  FOCUS_PRIMARY_TEAM: 'FOCUS_PRIMARY_TEAM',
  FOREGROUND_APP: 'FOREGROUND_APP',
  HANDLE_DEEP_LINK: 'HANDLE_DEEP_LINK',
  HANDLE_EXTERNAL_LINK: 'HANDLE_EXTERNAL_LINK',
  QUIT_APP: 'QUIT_APP',
  RELOAD: 'RELOAD',
  TOGGLE_FULL_SCREEN: 'TOGGLE_FULL_SCREEN',
  RUN_SPECS: 'RUN_SPECS',
  SHOW_ABOUT: 'SHOW_ABOUT',
  SHOW_RELEASE_NOTES: 'SHOW_RELEASE_NOTES',
  SHOW_WEBAPP_DIALOG: 'SHOW_WEBAPP_DIALOG',
  SIGN_OUT_TEAM: 'SIGN_OUT_TEAM',
  REFRESH_TEAM: 'REFRESH_TEAM',
  CONFIRM_AND_RESET_APP: 'CONFIRM_AND_RESET_APP',
  REPORT_ISSUE: 'REPORT_ISSUE',
  PREPARE_AND_REVEAL_LOGS: 'PREPARE_AND_REVEAL_LOGS',
  SIDEBAR_CLICKED: 'SIDEBAR_CLICKED',
  CLOSE_ALL_UPDATE_BANNERS: 'CLOSE_ALL_UPDATE_BANNERS'
};

export const NOTIFICATIONS = {
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  CLICK_NOTIFICATION: 'CLICK_NOTIFICATION',
  REPLY_TO_NOTIFICATION: 'REPLY_TO_NOTIFICATION'
};

export const SETTINGS = {
  INITIALIZE_SETTINGS: 'INITIALIZE_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_DEV_MODE: 'SET_DEV_MODE',
  SET_DEV_ENVIRONMENT: 'SET_DEV_ENVIRONMENT',
  SET_TITLE_BAR_HIDDEN: 'SET_TITLE_BAR_HIDDEN',
  ZOOM_IN: 'ZOOM_IN',
  ZOOM_OUT: 'ZOOM_OUT',
  RESET_ZOOM: 'RESET_ZOOM'
};

export const TEAMS = {
  ADD_NEW_TEAM: 'ADD_NEW_TEAM',
  ADD_NEW_TEAMS: 'ADD_NEW_TEAMS',
  REMOVE_TEAM: 'REMOVE_TEAM',
  REMOVE_TEAMS: 'REMOVE_TEAMS',
  UPDATE_TEAM_THEME: 'UPDATE_TEAM_THEME',
  UPDATE_TEAM_ICONS: 'UPDATE_TEAM_ICONS',
  UPDATE_UNREADS_INFO: 'UPDATE_UNREADS_INFO',
  UPDATE_TEAM_USAGE: 'UPDATE_TEAM_USAGE',
  UPDATE_TEAM_NAME: 'UPDATE_TEAM_NAME',
  UPDATE_TEAM_URL: 'UPDATE_TEAM_URL',
  UPDATE_USER_ID: 'UPDATE_USER_ID'
};

export const WINDOWS = {
  ADD_WINDOW: 'ADD_WINDOW',
  REMOVE_WINDOW: 'REMOVE_WINDOW'
};

export const BASE = {
  LOAD_LEGACY: 'LOAD_LEGACY',
  LOAD_PERSISTENT: 'LOAD_PERSISTENT'
};
